### ISSUE TITLE
Pinout documentation?

### ISSUE THREAD

**Issue by stevew817** [kwakeham/Maelstrom#2]
Thanks for all the effort and open-sourcing! Would it be possible to add hardware documentation here? I.e. BOM and schematic?

**Comment by cleeland** [comment]
I came here to ask the same question.  Even just details on the general hardware involved would be helpful because I can't tell from just the firmware what's being targeted.

**Comment by kwakeham** [comment]
Pins are listed in custom_board.h

#define LED_1R          16
#define LED_1G          12
#define LED_1B          14

#define LED_2R          11
#define LED_2G          9
#define LED_2B          10

#define LED_3R          19
#define LED_3G          30
#define LED_3B          31


#define BUTTONS_NUMBER 3

#define BUTTON_START   27
#define BUTTON_1       29
#define BUTTON_2       28
#define BUTTON_3       27
#define BUTTON_STOP    29
#define BUTTON_PULL    NRF_GPIO_PIN_PULLUP


These are all the standard nordic ones, except the triac and crossover were poorly hardcoded into the triac.h file as 

#define PIN_ZC 18 //old 11
#define PIN_OUT 20  //old 12

These pinouts relate to the nrf52832 chip. Check the Module BL652-SA used. If you have a PCB these are all listed on the underside in the silk.

**Comment by cleeland** [comment]
Thanks!

To be clear, there's no schematic or board drawings available, correct?
